apiVersion: v1
kind: PersistentVolume
metadata:
  name: meu-pv
spec:
  storageClassName: ligacao-pv-e-claim
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k3dmongodata"