apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:5.0.5
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: "/data/db"
              name: task-pv-storage
          envFrom:
          - secretRef:
              name: {{ .Release.Name }}-secret-mongo
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: meu-claim